name: Forward
on:
  push:
    branches:
      - master
      - stable

jobs:
  VOTCA:
    runs-on: ubuntu-latest
    steps:
      - name: Update submodule
        uses: votca/actions/forward@master
        with:
          module: ${{ github.repository }}
          token: ${{ secrets.VOTCA_BOT_TOKEN }}

